### ISSUE TITLE
Media Element Stops working when window moved to non-primary screen

### ISSUE THREAD

**Issue by kott** [IMDC/LiveDescribe-Desktop#9] opened 2013-08-27 19:37 UTC
If the user has multiple monitors, the video element stops working once the window has been brought to this monitor.  This could be a possible issue with .NET 4.0 as stated here: http://stackoverflow.com/questions/4189660/why-does-wpf-mediaelement-not-work-on-secondary-monitor

**Comment by dmaugeri** [comment] 2013-08-29 01:30
I tried reproducing the bug on my computer and it seemed to work as it should. It might be because you're referencing .net 4.0 references instead of 4.5.

**Comment by vserrago** [comment] 2014-05-22 18:05
Seems to be fixed as of May 22nd

**Closed as completed by vserrago** 2014-05-22 18:05 UTC
Labels: bug
